#!/bin/bash

ver=2009.8.24

opentheory=../opentheory

adir=$opentheory/test/articles/hol-light
if ! test -d $adir ; then echo "$adir not a directory" ; exit 1 ; fi

prog=$opentheory/bin/mlton/opentheory
if ! test -x $prog ; then echo "$prog not an executable" ; exit 1 ; fi

int=$opentheory/test/interpretations/hol-light.int
if ! test -r $int ; then echo "$int not readable" ; exit 1 ; fi
if test $int -nt opentheory/hol-light.int
then
    perl -ne 'chomp $_; if ($_ !~ /^ *([#]|$)/) { print STDOUT "$_\n"; }' < $int > opentheory/hol-light.int
fi

rdir=$opentheory/test/opentheory
if ! test -d $rdir ; then echo "$rdir not a directory" ; exit 1 ; fi

echo '#use "hol.ml";;' | ocaml

cat opentheory/bool-true-def.art \
    opentheory/bool-true-thm.art \
    opentheory/bool-true-aux.art \
    opentheory/bool-and-def.art \
    opentheory/bool-and-aux.art \
    opentheory/bool-imp-def.art \
    opentheory/bool-imp-aux.art \
    opentheory/bool-forall-def.art \
    opentheory/bool-forall-aux.art \
    opentheory/bool-exists-def.art \
    opentheory/bool-exists-aux.art \
    opentheory/bool-or-def.art \
    opentheory/bool-or-aux.art \
    opentheory/bool-false-def.art \
    opentheory/bool-not-def.art \
    opentheory/bool-not-aux.art \
    opentheory/bool-exists-unique-def.art \
    opentheory/bool-exists-unique-aux.art > $adir/bool.art
cat opentheory/tactics-aux.art > $adir/tactics.art

for thy in $(ls -tr opentheory/*.thy)
do
    echo
    base=$(basename $file .thy)
    pdir=$rdir/packages/hol-light-$base-$ver

    if test -d $pdir
    then
        sum=opentheory/$base.sum

        if test $thy -nt $sum
        then
            echo "compiling" $thy

            $prog compile --summary-text $sum --article $pdir/$file $thy || exit 1
            ls -l $file
            ls -l $pdir/$file
        else
            echo "skipping" $file "(up to date)"
        fi
    else
        echo -n "skipping "
        ls -l $thy
    fi
done

echo

# cd $opentheory
# make all-generic-theories || exit 1
