#!/bin/bash

opentheory=../opentheory

adir=$opentheory/test/articles/hol-light
if ! test -d $adir ; then echo "$adir not a directory" ; exit 1 ; fi

prog=$opentheory/bin/mlton/opentheory
if ! test -x $prog ; then echo "$prog not an executable" ; exit 1 ; fi

int=$opentheory/test/interpretations/hol-light.int
if ! test -r $int ; then echo "$int not readable" ; exit 1 ; fi
if test $int -nt opentheory/hol-light.int
then
    perl -ne 'chomp $_; if ($_ !~ /^ *([#]|$)/) { print STDOUT "$_\n"; }' < $int > opentheory/hol-light.int
fi

theories=$opentheory/test/theories
if ! test -d $theories ; then echo "$theories not a directory" ; exit 1 ; fi

repo=$opentheory/test/repo
if ! test -d $repo ; then echo "$repo not a directory" ; exit 1 ; fi

echo '#use "hol.ml";;' | ocaml

cat opentheory/bool-true-thm.art > $adir/bool.art
cat opentheory/tactics-aux.art > $adir/tactics.art

for thy in $(ls -tr opentheory/*.thy)
do
    base=$(basename $thy .thy)
    tdir=$theories/$base

    if ! test -d $tdir
    then
        echo "making new" $base "theory directory"
        mkdir $tdir

        echo $base.art > $tdir/.gitignore

        tthy=$tdir/$base.thy
        echo "name: $base" > $tthy
        echo "version: 1.0" >> $tthy
        echo -n "description: HOL Light theory segment $base extracted on " >> $tthy
        date "+%Y-%m-%d." >> $tthy
        echo "author: Joe Hurd <joe@gilith.com>" >> $tthy
        echo "license: HOLLight" >> $tthy
        echo >> $tthy
        echo "main {" >> $tthy
        echo "  article: \"$base.art\"" >> $tthy
        echo "}" >> $tthy
    fi

    sum=opentheory/$base.sum

    if test $thy -nt $sum
    then
        art=$tdir/$base.art

        echo "compiling" $base

        $prog compile --summary-text $sum --article $art $thy || exit 1
        ls -l opentheory/$base.art
        ls -l $art
        echo
    else
        echo "skipping " $base "(up to date)"
    fi
done

echo

# cd $opentheory
# make all-generic-theories || exit 1
